# Generated by Django 2.1.14 on 2020-02-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='gender',
            new_name='post_type',
        ),
    ]
